### ISSUE TITLE
Handle new Notifications correctly with Actions

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#106]
Currently the notifications are not tied to new actions when they're created which they should be. You need to create a new action whenever you create a new notification and you need to tie the action key to the Notification's action key variable.

**Comment by JDNdeveloper** [comment]
I did this in MainActivity when new notifications are created. Make sure this happens in ReminderActivity when new notifications are created inside of there.

**Comment by JoetheSoda** [comment]
I haven't done this in notification, did you do it there too?

**Comment by JDNdeveloper** [comment]
I did it in Main when you add a new one. You'll need to do this in Reminder
Activity.

**Comment by JoetheSoda** [comment]
When I changed how creating a new notification works in main activity this must have gotten lost, because when I tested it, by creating a notification in MainActivity it said the actionKey was "Failed_Action_X" x being a number, I fixed this so now its there, and it doesnt say it has a failed action key anymore.
