### ISSUE TITLE
When building days of the week, use proper Notification.java standard

### ISSUE THREAD

**Issue by JDNdeveloper** [JDNdeveloper/Off-By-One#135]

**Comment by JoetheSoda** [comment]
I am not sure what the problem is here, can you go into some detail

**Comment by JDNdeveloper** [comment]
Not sure if there's a problem, just make sure to read my documentation and
follow the standards that I use. To set Monday use Calendar.MONDAY etc.

**Comment by JoetheSoda** [comment]
Days of the week follows the standard. However, I don't use Calendar.MONDAY for monday, because I needed Sunday to be represented by 0 in my code, because of how Dialogs with multi-choice selections work, whereas Calendar.SUNDAY starts at 1. When adding/removing a day to the days that are repeated, this is accounted for so there is not an Off-By-One error.
